#!/usr/bin/env python3


import argparse
import json
from urllib.parse import urlparse
from aws_requests_auth.boto_utils import BotoAWSRequestsAuth
import boto3
import requests


cloudformation = boto3.client("cloudformation")


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["start", "status"])
    parser.add_argument("stack")

    return parser.parse_args()


def get_endpoint(stack_name: str) -> str:
    stack = cloudformation.describe_stacks(StackName=stack_name)["Stacks"][0]
    for output in stack["Outputs"]:
        if output["OutputKey"] == "ApiEndpoint":
            return output["OutputValue"]


def get_auth(endpoint: str):
    url = urlparse(endpoint)
    region = boto3.session.Session().region_name
    return BotoAWSRequestsAuth(aws_host=url.netloc,
                               aws_region=region,
                               aws_service='execute-api')


def main(command: str, stack_name: str):
    endpoint = get_endpoint(stack_name)+"/"
    auth = get_auth(endpoint)

    if command == "start":
        response = requests.put(endpoint, auth=auth)
    elif command in "status":
        response = requests.get(endpoint, auth=auth)
    obj = response.json()
    print(json.dumps(obj, indent=2))


if __name__ == "__main__":
    args = get_args()
    main(args.command, args.stack)